# Generated by Django 3.2 on 2023-09-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Orderd'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
