# Generated by Django 3.2 on 2023-08-23 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
