# Generated by Django 3.2 on 2023-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
    ]
