# Generated by Django 3.2 on 2023-09-04 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=32, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
